# -*- mode: ruby -*-
# vi: set ft=ruby :

# Purpose: lab machine for Java 8 

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "javadev-jdk8-20130303"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = 
	"https://s3-eu-west-1.amazonaws.com/omegapoint-vm-dframyb0sr714xrk/vagrantboxes/ubuntu-java8-desktop-20140303.box"

  # Enable provisioning with shell script
  # config.vm.provision "shell", path: "noop.sh"

  # Boot to desktop mode
  config.vm.provider :virtualbox do |vb|
     vb.gui = true
  end
end
  
